@startuml

box "PISP"
    participant "PISP Server" as D1
end box
box "Mojaloop"
    participant "Thirdparty API Adapter" as 3P
    participant "Central Event Processor" as CEP
end box
box "DFSP A"
    participant "DFSP A\n(Payer)" as D2
end box


rnote over D1 #Light
**""POST /thirdpartyRequests/transactions""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
    transactionRequestId: "1234",
    ...
}
end note
D1 -> 3P: ""POST /thirdpartyRequests/transactions""
3P -> CEP: Please start listening for \n *things* related to the transactionRequestId of ""1234""
3P --> D1: ""202 Accepted""
3P -> D2: ""POST /thirdpartyRequests/transactions""

... **Transaction initiation takes place** ...
@enduml
