@startuml

box "Mojaloop"
    participant "Central Event Processor" as CEP
    participant "ML API Adapter" as ML
    participant "Central Ledger" as CL
end box
box "DFSP A"
    participant "DFSP A\n(Payer)" as D2
end box
box "DFSP B"
    participant "DFSP B\n(Payee)" as D3
end box


... **User signs the authorization, DFSPA verifies it, and issues a ""POST /transfers""** ...

rnote over D2 #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
    transferId: "9876",
    **transactionId: 5678**
    ...
}
end note
D2 -> ML: ""POST /transfers""
ML --> D2: 202 Accepted

' TODO: tidy and clarify these steps
' it could be the ml-api-adapters event that triggers the CEP
' we need to look a little more into how the central-ledger's handlers work

ML -> CL: Transfer is going ahead... can you check these details?
CL -> ML: Yep, looks good to me (Prepare Notification)

CL -> CEP: Here's a transfer that looks like it might go ahead.

ML -> D3: ""POST /transfers""

CEP -> CEP: That transfer has a transactionId of ""5678""
CEP -> CEP: It had a transferId of ""9876""\n let's now listen for transfers with id ""5678""

note over CEP
The CEP now knows that it needs to listen for transfers with id  ""9876""
in order to fulfil it's original subscription
end note

@enduml
