@startuml

hide empty description

''' txReq
[*] --> txReqCreated: **ThirdpartyTransactionRequest Subscription**
txReqCreated: Listeners:
txReqCreated: ""transactionRequestId""

''' auth
txReqCreated --> authWaiting: **ThirdpartyAuthorizationRequest**

authWaiting: Listeners:
authWaiting: ""transactionRequestId""
authWaiting: ""transactionId""

''' transfer
authWaiting --> transferWaiting: **Transfer Prepare Notification**

transferWaiting: Listeners:
transferWaiting: ""transactionRequestId""
transferWaiting: ""transferId""

transferWaiting --> transferComplete: **Transfer Fulfil Notification**

transferComplete --> [*]


@enduml
