@startuml

title PISP Linking: Discovery

box "Mobile device"
    participant App
end box

box "PISP"
    participant PISP
end box

box "Mojaloop"
    participant Switch
end box

participant DFSP

autonumber 1 "<b>DISC-#</b>"
activate PISP

...

note over App, DFSP
  The user will be prompted in the PISP App for the unique ID they use with their DFSP. This could be a username, MSISDN, email address, etc.
end note

...

PISP -> Switch ++: ""GET /parties/OPAQUE/username1234""\n\
  ""  FSIOP-Source: PISP""\n\
  ""  FSIOP-Destination: DFSP""
Switch --> PISP: ""202 Accepted""
deactivate PISP

Switch -> DFSP ++: ""GET /parties/OPAQUE/username1234""
DFSP --> Switch: ""202 Accepted""
deactivate Switch

DFSP -> Switch ++: ""PUT /parties/OPAQUE/username1234 { [""\n\
  ""  { id: "dfspa.username.1234", currency: "ZAR" },""\n\
  ""  { id: "dfspa.username.5678", currency: "USD" }""\n\
  ""] }""
Switch --> DFSP: ""200 OK""
deactivate DFSP

Switch -> PISP ++: ""PUT /parties/OPAQUE/username1234 { [""\n\
  ""  { id: "dfspa.username.1234", currency: "ZAR" },""\n\
  ""  { id: "dfspa.username.5678", currency: "USD" }""\n\
  ""] }""
PISP --> Switch: ""200 OK""
deactivate Switch
deactivate PISP

...

note over App, DFSP
  The PISP can now present a list of possible accounts to the user for pairing.
end note

@enduml
