@startuml

title PISP Linking: Request consent (Web)

participant "PISP" as PISP

box "Mojaloop"
    participant Switch
end box

participant DFSP

actor User
participant WebBrowser
participant DFSPAuthorizeSimulator

autonumber 1 "<b>REQ-#</b>"

activate PISP

...

note over PISP, DFSP
    The user initiated some sort of account linking by choosing the appropriate DFSP from a screen inside the PISP application.
end note

...

== Success case ==

PISP -> Switch ++: ""POST /consentRequests""\n\
  ""  FSIOP-Source: pispa""\n\
  ""  FSIOP-Destination: dfspa""\n\
  "" {""\n\
  ""  consentRequestId: "456",""\n\
  ""  scopes: [ ""\n\
  ""    { **accountId: "dfsp.username.1234", // This is *optional* for web.**""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""    { accountId: "dfsp.username.5678",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""  ],""\n\
  ""  authChannels: [ "Web", "OTP" ],""\n\
  ""  callbackUri: "pisp-app://callback..."""\n\
  ""}""
Switch --> PISP: ""202 Accepted""
deactivate PISP

Switch -> DFSP ++:  ""POST /consentRequests""\n\
  ""  FSIOP-Source: pispa""\n\
  ""  FSIOP-Destination: dfspa""\n\
  "" {""\n\
  ""  consentRequestId: "456",""\n\
  ""  scopes: [ ""\n\
  ""    { accountId: "dfsp.username.1234",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""    { accountId: "dfsp.username.5678",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""  ],""\n\
  ""  authChannels: [ "Web", "OTP" ],""\n\
  ""  callbackUri: "pisp-app://callback..."""\n\
  ""}""
autonumber 1 "<b>DFSP-#</b>"

DFSP -> DFSP: Verify the consentRequests is valid or not?
autonumber 1 "<b>SIM-#</b>"
DFSP -> DFSPAuthorizeSimulator: ""POST /store/consentRequests/456""
DFSPAuthorizeSimulator -> DFSPAuthorizeSimulator: store consentRequest details
DFSPAuthorizeSimulator -> DFSP: 201 Created
autonumber 4 "<b>REQ-#</b>"

DFSP --> Switch: ""202 Accepted""
deactivate Switch

DFSP -> Switch ++: ""PUT /consentRequests/456""\n\
  ""  FSIOP-Source: dfspa""\n\
  ""  FSIOP-Destination: pispa""\n\
  "" {""\n\
  ""  scopes: [ ""\n\
  ""    { accountId: "dfsp.username.1234",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""    { accountId: "dfsp.username.5678",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""  ],""\n\
  ""  authChannels: [ "Web" ],""\n\
  ""  callbackUri: "pisp-app://callback..."""\n\
  ""  **authUri: "dfspa.com/authorize?consentRequestId=456" // This is new!**""\n\
  ""}""
' TODO: Should this be 200 OK? or 202 Accepted?
Switch --> DFSP: ""202 Accepted""
deactivate DFSP

Switch -> PISP ++: ""PUT /consentRequests/456""\n\
  ""  FSIOP-Source: dfspa""\n\
  ""  FSIOP-Destination: pispa""\n\
  "" {""\n\
  ""  scopes: [ ""\n\
  ""    { accountId: "dfsp.username.1234",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""    { accountId: "dfsp.username.5678",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""  ],""\n\
  ""  authChannels: [ "Web" ],""\n\
  ""  callbackUri: "pisp-app://callback..."""\n\
  ""  **authUri: "dfspa.com/authorize?consentRequestId=456" // This is new!**""\n\
  ""}""
PISP --> Switch: ""200 OK""
deactivate Switch

note over PISP, DFSP
  At this point, the PISP knows that the Web authChannel is in use and the PISP App should redirect the user to the provided ""authUri"".
end note

autonumber 4 "<b>SIM-#</b>"

PISP -> WebBrowser: ""window.location <- authUri ==> ** GET dfspa.com/authorize?consentRequestId=456**&callbackUri=pisp-app://callback...""
deactivate PISP
activate WebBrowser
activate User
WebBrowser -> DFSPAuthorizeSimulator: GET **/authorize?consentRequestId=456&callbackUri=pisp-app://callback...**
DFSPAuthorizeSimulator -> WebBrowser: 200 OK: send **/authorize** single page application (SPA)
WebBrowser -> WebBrowser: RENDER: **login form**
User -> WebBrowser: SUBMIT **username & password**
WebBrowser -> DFSPAuthorizeSimulator: ""POST /login""\n\
  ""{""\n\
  ""  username,""\n\
  ""  password,""\n\
  ""}""
DFSPAuthorizeSimulator -> DFSPAuthorizeSimulator: verify User's credentials \ntake action on **TTK defined rule for username**"
DFSPAuthorizeSimulator -> WebBrowser: 201 OK: user authorized
WebBrowser -> DFSPAuthorizeSimulator: GET /store/consentRequests/456
DFSPAuthorizeSimulator -> DFSPAuthorizeSimulator: find consentRequest details for id=456
DFSPAuthorizeSimulator -> WebBrowser: 200 OK: consent requests details in response payload
WebBrowser -> WebBrowser: RENDER **ask the User to grant consent** for **consentRequestId=456**\n
User -> WebBrowser: SUBMIT: **consent granted**
WebBrowser -> DFSPAuthorizeSimulator: ""POST /authorize""\n\
  ""{""\n\
  ""  consentRequestId=456"",\n\
  ""  username,""\n\
  ""}""
DFSPAuthorizeSimulator -> DFSPAuthorizeSimulator: generate a **secret="some-secret"**\ntake action on **TTK defined rule for username**
DFSPAuthorizeSimulator -> WebBrowser: 201 OK: response: { **secret:"some-secret"**" }
WebBrowser -> User: redirects to callbackUri="pisp-app://callback...?**secret=some-secret**"
deactivate User

== Failure case ==

autonumber 1 "<b>REQ-#</b>"
PISP -> Switch ++: ""POST /consentRequests""\n\
  ""  FSIOP-Source: pispa""\n\
  ""  FSIOP-Destination: dfspa""\n\
  "" {""\n\
  ""  consentRequestId: "456",""\n\
  ""  scopes: [ ""\n\
  ""    { **accountId: "dfsp.username.1234", // This is *optional* for web.**""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""    { accountId: "dfsp.username.5678",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""  ],""\n\
  ""  authChannels: [ "Web", "OTP" ],""\n\
  ""  callbackUri: "pisp-app://callback..."""\n\
  ""}""

Switch --> PISP: ""202 Accepted""
deactivate PISP

Switch -> DFSP ++:  ""POST /consentRequests""\n\
  ""  FSIOP-Source: pispa""\n\
  ""  FSIOP-Destination: dfspa""\n\
  "" {""\n\
  ""  consentRequestId: "456",""\n\
  ""  scopes: [ ""\n\
  ""    { accountId: "dfsp.username.1234",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""    { accountId: "dfsp.username.5678",""\n\
  ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
  ""  ],""\n\
  ""  authChannels: [ "Web", "OTP" ],""\n\
  ""  callbackUri: "pisp-app://callback..."""\n\
  ""}""
autonumber 1 "<b>DFSP-#</b>"

DFSP -> DFSP: Verify the consentRequests is valid or not?

note over PISP, DFSP
  We respond with an error that the consentRequests is invalid so the PISP can inform the user.
end note

autonumber 4 "<b>REQ-#</b>"
DFSP -> Switch ++: ""PUT /consentRequests/456/error""\n\
  ""  FSIOP-Source: dfspa""\n\
  ""  FSIOP-Destination: pispa""\n\
  ""{""\n\
  ""  errorInformation : { ""\n\
  ""    errorCode: "7204", ""\n\
  ""    errorDescription: "FSP does not support any requested scope actions" ""\n\
  ""  } ""\n\
  ""}""
Switch --> DFSP: ""200 OK""
deactivate DFSP

Switch -> PISP ++: ""PUT /consentRequests/456/error""\n\
  ""  FSIOP-Source: dfspa""\n\
  ""  FSIOP-Destination: pispa""\n\
  ""{""\n\
  ""  errorInformation : { ""\n\
  ""    errorCode: "7204", ""\n\
  ""    errorDescription: "FSP does not support any requested scope actions" ""\n\
  ""  } ""\n\
  ""}""
PISP --> Switch: ""200 OK""

@enduml
