@startuml
title PISP Linking: Authentication
!include participants_detailed.iuml

... Alice chooses DFSP A ...

autonumber 7 "<b>DISC-#</b>"
Alice -> App: My account is with DFSP A.

autonumber 1 "<b>AUTH-A-#</b>"
note over Alice, DFSP
    This flow is based on Pushed Authorization Requests:
    https://tools.ietf.org/html/draft-ietf-oauth-par-01.

    The PAR interaction should be done via a Mojaloop APIs resource called /authorizationRequests
end note

    App -> Server: Get authorization to act on behalf of Alice from DFSP A
    Server -> Switch: POST /authorizationRequests/{ID}\n { supportedAuthenticationChannels: [Web, OTP],\n scopes: [balanceEnquiry, accountList, sendTransfer],\n callbackUrl: pisp-app://callback ... }
    Switch --> Server: 201 Created
    Switch -> DFSP: POST /authorizationRequests/{ID}\n { supportedAuthenticationChannels: [Web, OTP],\n scopes: [balanceEnquiry, accountList, sendTransfer],\n callbackUrl: pisp-app://callback ... }
    DFSP --> Switch: 201 Created
    DFSP -> Switch: GET /authorizations/{ID}\n?authenticationType=Web\n&url=https://dfspa.com/auth?request_uri={ID}
    Switch --> DFSP: 200 Success
    Switch -> Server: GET /authorizations/{ID}\n?authenticationType=Web\n&url=https://dfspa.com/auth?request_uri={ID}
    Server --> Switch: 200 Success
    Server -> App: Redirect user to:\n https://dfspa.com/auth?request_uri={ID}
@enduml