@startuml
title PISP Linking: Authentication
box "Mobile device"
    actor Alice
    participant "PISP App" as App    
end box
box "PISP"
participant "PISP Server" as Server
end box
box "DFSP A"
    participant "DFSP A" as DFSP
end box

Alice -> App: My account is with DFSP A.

autonumber 1 "<b>AUTH-#</b>"
      note over Server, DFSP
        Calls between the PISP and DFSP will go through the switch.
        FIDO related calls to the DFSP will also likely be forwarded
        to a central FIDO Server. 

        These have been left out here for simplicity
      end note
    group Auth-N and Consent
    App -> Server: Get authorization to act \non behalf of Alice from DFSP A
    Server -> DFSP: Can I get auth-z to act on Alice's behalf?
    DFSP --> Server: Redirect Alice to my website\n so I can ask her
    Server --> App: Redirect user to DFSPA's \nwebsite using this request ID
    App --> Alice: You must login to DFSPA website\n to grant us access to your account
    Alice -> DFSP: Login to DFSP website (auth-n)
    note over Alice, DFSP: Alice chooses which account the PISP will \nhave access to via a list on the DFSP website
    Alice -> DFSP: Select account and grant consent (auth-z)
    DFSP --> Server: Alice has granted auth-z for you \nto access her Savings account
    end
    group FIDO Enrollment
      Server -> DFSP: Give me a challange to create a credential\n for Alice's Savings account
      DFSP --> Server: Here you go
      Server --> App: Use this challenge to create\n a new FIDO credential for Alice
      App -> Alice: Register your fingerprint to \nauthenticate when transacting in future
      Alice --> App: <scan fingerprint>
      App -> Server: Enroll this credential for \nAlice's Savings account at DFSP A
      Server -> DFSP: Enroll this credential for Alice's Savings account
      DFSP --> Server: Done!
    end
    Server -> App: Success
    App -> Alice: Success
@enduml