@startuml

!pragma teoz true

title PISP Linking: Grant consent

participant "PISP" as PISP

box "Mojaloop"
    participant "Thirdparty-API-Adapter" as Switch
    participant "Account Lookup Service" as ALS
    participant "Auth Service" as Auth
end box

participant "DFSP" as DFSP

autonumber 1 "<b>GRANT-#</b>"

== Success case ==

DFSP -> DFSP: Get scopes that were stored\nin "Request consent" step.

DFSP -> Switch ++: ""POST /consents""\n\
""  FSIOP-Source: dfspa""\n\
""  FSIOP-Destination: pispa""\n\
""  {""\n\
    ""  consentId: "123",""\n\
    ""  consentRequestId: "456",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""}""
Switch --> DFSP: ""202 Accepted""
deactivate DFSP

Switch -> PISP ++: ""POST /consents""\n\
""  FSIOP-Source: dfspa""\n\
""  FSIOP-Destination: pispa""\n\
""   {""\n\
    ""  consentId: "123",""\n\
    ""  consentRequestId: "456",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""}""

PISP --> Switch: ""202 Accepted""
deactivate Switch
deactivate PISP

== Failure case ==

DFSP -> DFSP: Unable to fetch stored scopes

DFSP -> Switch ++: ""PUT /consentRequests/456/error""\n\
  ""  FSIOP-Source: dfspa""\n\
  ""  FSIOP-Destination: pispa""\n\
  ""{""\n\
  ""  errorInformation : { ""\n\
  ""    errorCode: "7207", ""\n\
  ""    errorDescription: "FSP failed retrieve scopes for consent request" ""\n\
  ""  } ""\n\
  ""}""
Switch --> DFSP: ""200 OK""
deactivate DFSP

Switch -> PISP ++: ""PUT /consentRequests/456/error""\n\
  ""  FSIOP-Source: dfspa""\n\
  ""  FSIOP-Destination: pispa""\n\
  ""{""\n\
  ""  errorInformation : { ""\n\
  ""    errorCode: "7207", ""\n\
  ""    errorDescription: "FSP failed retrieve scopes for consent request" ""\n\
  ""  } ""\n\
  ""}""
PISP --> Switch: ""200 OK""
deactivate Switch
deactivate PISP

@enduml
