@startuml

!pragma teoz true

title PISP Linking: Credential registration (challenge)

participant "PISP" as PISP

box "Mojaloop"
    participant Switch
    participant "Auth Service" as Auth
end box

participant "DFSP" as DFSP

autonumber 1 "<b>CRED-#</b>"

PISP -> Switch ++: ""POST /consents/123/generateChallenge {}""
Switch --> PISP: ""202 Accepted""
deactivate PISP

Switch -> Auth ++: ""POST /consents/123/generateChallenge {}""
Auth --> Switch: ""202 Accepted""
deactivate Switch

Auth -> Auth: Generate a new challenge.
Auth -> Switch ++: ""PUT /consents/123 {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "PISP",""\n\
    ""  participantId: "DFSP",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  **credential: { // This is new!**""\n\
    ""    **id: null,**""\n\
    ""    **credentialType: "FIDO", // TODO: Is this required?**""\n\
    ""    **status: "PENDING",**""\n\
    ""    **challenge: {**""\n\
    ""      **payload: base64(...),**""\n\
    ""      **signature: null,**""\n\
    ""    **},**""\n\
    ""    **payload: null,**""\n\
    ""  **}**""\n\
    ""}""
Switch --> Auth: ""202 Accepted""
deactivate Auth

Switch -> PISP ++: ""PUT /consents/123 {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "PISP",""\n\
    ""  participantId: "DFSP",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  **credential: { // This is new!**""\n\
    ""    **id: null,**""\n\
    ""    **credentialType: "FIDO",**""\n\
    ""    **status: "PENDING",**""\n\
    ""    **challenge: {**""\n\
    ""      **payload: base64(...),**""\n\
    ""      **signature: null,**""\n\
    ""    **},**""\n\
    ""    **payload: null,**""\n\
    ""  **}**""\n\
    ""}""
PISP --> Switch: ""202 Accepted""
deactivate Switch

@enduml
