@startuml

!pragma teoz true

title PISP Linking: Credential registration (verification)

participant "PISP" as PISP

box "Mojaloop"
    participant Switch
    participant "Auth Service" as Auth
end box

participant "DFSP" as DFSP

autonumber 10 "<b>CRED-#</b>"

...

note over PISP, DFSP
    The PISP uses the FIDO registration flow to generate a new keypair and sign the challenge, relying on the user performing an "unlock action" on their mobile device.
end note

...

PISP -> Switch ++: ""PUT /consents/123""\n\
""  FSIOP-Source: pispa""\n\
""  FSIOP-Destination: auth.dfspa""\n\
""  {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "pispa",""\n\
    ""  participantId: "dfspa",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  credential: {""\n\
    ""    **id: "9876", // This is new!**""\n\
    ""    credentialType: "FIDO",""\n\
    ""    status: "PENDING",""\n\
    ""    challenge: {""\n\
    ""      payload: base64(...),""\n\
    ""      **signature: base64(...), // This is new!**""\n\
    ""    },""\n\
    ""    **payload: base64(...), // This is new!**""\n\
    ""  }""\n\
    ""}""
Switch --> PISP: ""202 Accepted""
deactivate PISP

Switch -> Auth ++: ""PUT /consents/123""\n\
""  FSIOP-Source: pispa""\n\
""  FSIOP-Destination: auth.dfspa""\n\
""   {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "pispa",""\n\
    ""  participantId: "dfspa",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  credential: {""\n\
    ""    **id: "9876", // This is new!**""\n\
    ""    credentialType: "FIDO",""\n\
    ""    status: "PENDING",""\n\
    ""    challenge: {""\n\
    ""      payload: base64(...),""\n\
    ""      **signature: base64(...), // This is new!**""\n\
    ""    },""\n\
    ""    **payload: base64(...), // This is new!**""\n\
    ""  }""\n\
    ""}""
Auth --> Switch: ""202 Accepted""
deactivate Switch

Auth -> Auth: Verify the signature checks out.\nSave the credential.
Auth -> Switch ++: ""PUT /consents/123""\n\
""  FSIOP-Source: auth.dfspa""\n\
""  FSIOP-Destination: pisp""\n\
""   {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "pispa",""\n\
    ""  participantId: "dfspa",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  credential: {""\n\
    ""    id: "9876",""\n\
    ""    credentialType: "FIDO",""\n\
    ""    **status: "VERIFIED", // This is new!**""\n\
    ""    challenge: {""\n\
    ""      payload: base64(...),""\n\
    ""      signature: base64(...),""\n\
    ""    },""\n\
    ""    payload: base64(...),""\n\
    ""  }""\n\
    ""}""
Switch --> Auth: ""200 OK""
deactivate Auth

Switch -> PISP ++: ""PUT /consents/123""\n\
""  FSIOP-Source: auth.dfspa""\n\
""  FSIOP-Destination: pisp""\n\
""    {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "pispa",""\n\
    ""  participantId: "dfspa",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  credential: {""\n\
    ""    id: "9876",""\n\
    ""    credentialType: "FIDO",""\n\
    ""    status: "VERIFIED",""\n\
    ""    challenge: {""\n\
    ""      payload: base64(...),""\n\
    ""      signature: base64(...),""\n\
    ""    },""\n\
    ""    payload: base64(...),""\n\
    ""  }""\n\
    ""}""
& Switch -> DFSP ++: ""PUT /consents/123""\n\
""  FSIOP-Source: auth.dfspa""\n\
""  FSIOP-Destination: dfspa""\n\
""  {""\n\
    ""  requestId: "456",""\n\
    ""  initiatorId: "pispa",""\n\
    ""  participantId: "dfspa",""\n\
    ""  scopes: [ ""\n\
    ""    { accountId: "dfsp.username.1234",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""    { accountId: "dfsp.username.5678",""\n\
    ""      actions: [ "accounts.transfer", "accounts.getBalance" ] },""\n\
    ""  ],""\n\
    ""  credential: {""\n\
    ""    id: "9876",""\n\
    ""    credentialType: "FIDO",""\n\
    ""    status: "VERIFIED",""\n\
    ""    challenge: {""\n\
    ""      payload: base64(...),""\n\
    ""      signature: base64(...),""\n\
    ""    },""\n\
    ""    payload: base64(...),""\n\
    ""  }""\n\
    ""}""
PISP --> Switch --: ""200 OK""
& DFSP --> Switch --: ""200 OK""
deactivate Switch

@enduml
