@startuml OAuth 2: Recovation
autonumber
title OAuth 2: Revocation

actor User
participant "Web App" as App
box "Service"
  participant "Authz Server" as AuthService
  participant "Resource Server" as ResourceService
end box

...

App -> AuthService: Can I have an access token for Resource #1234?\nHere's my authorization grant.\n""GET /accessToken?resource=1234&authGrant=~*~*~*""
AuthService --> App: Sure. Here's an access token and a refresh token.\n""200 OK. { accessToken: ~*~*~*, refreshToken: ~*~*~* }""

note over App, AuthService
  Continue from here with a valid access token.
end note

... 

group User revokes access token
  User -> AuthService: Can you show me the access tokens you have for me?\n""GET /accessTokens""
  AuthService --> User: Sure. We only have one (#5678) granted 2 minutes ago, expiring in 1 hour.\n""Access Token { id: 5678, grantTime: ..., expireTime: ... }""
  User -> AuthService: Can you revoke token #5678?\n""DELETE /accessTokens/5678""
  AuthService --> User: Sure. We'll do that right away. It might take a bit to kick in though...\n""200 OK.""
end group

...

note over App, AuthService
  Until the access token expires, the resource will remain accessible
  to the application.
end note

...

group Eventually, access fails due to expired access token
  User -> App: I'd like to see Resource #1234.\n""GET /resources/1234""
  App -> ResourceService: My user wants to see Resource #1234. Here's my access token.\n""GET /resources/1234?accessToken=~*~*~*""
  ResourceService -->x App: Sorry, that access token has expired.\n""403 Access Denied.""
end group

group Refreshing fails also due to revokation
  App -> AuthService: I'd like to refresh my access token. Here's my refresh token.\n""GET /accessToken?resource=1234&refreshToken=~*~*~*""
  AuthService -->x App: Sorry, that token has been revoked.\n""203 Access Denied.""
end group

@enduml