@startuml

box "Mojaloop"
  participant Switch as S
end box

box "SDK-scheme-adapter"
  participant "SDK-Incoming" as Sin
  participant "SDK-Outgoing" as Sout
end box
box "thirdparty-sdk"
  participant "Thirdparty-Incoming" as Tin
  participant "Thirdparty-Outgoing" as Tout
end box

participant PISP as P

activate Tout
activate P
P -> Tout: start workflow
Tout -> Sout: sync GET <urlResource>
activate Sout
Sout -> Sout: register to PUB/SUB channel\nand wait for response
Tout -> Tout: wait on response from sync call

Sout -> S: GET <urlResource>
activate S
S --> Sout: 200 OK
deactivate Sout
S -> S: finding party information

S -> Sin: PUT <urlResource>
deactivate S
activate Sin
Sin -> Sout: publish PUT payload to PUB/SUB channel
deactivate Sin
activate Sout
Sout -> Tout: send PUT payload as http response
deactivate Sout

Tout -> Tout: consume PUT payload received from call\nand continue the workflow
Tout -> P: return workflow result to PISP
@enduml
