openapi: 3.0.2
info:
  version: '1.1'
  title: Open API for FSP Interoperability (FSPIOP)
  description: >-
    Based on API Definition.docx updated on 2018-03-13 Version 1.0. Note - The
    API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP
    header.
  license:
    name: Open API for FSP Interoperability (FSPIOP)
paths:
  '/requests/{ID}':
    get:
      description: Test support method. Allows the caller to see the body of a previous request
      summary: getRequestsById
      tags:
        - test
      operationId: getRequestsById
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
  '/callbacks/{ID}':
    get:
      description: Test support method. Allows the caller to see the body of a previous callback
      summary: getRequestsById
      tags:
        - test
      operationId: getCallbackById
      parameters:
        - $ref: '#/components/parameters/ID'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
components:
  parameters:
    ID:
      name: ID
      in: path
      required: true
      schema:
        type: string
