@startuml

title Transfer: 1.3 Final transfer

box "PISP"
participant "PISP Server" as D1
end box
box "Mojaloop"
    participant Switch as S
end box
box "DFSP A"
    participant "DFSP A\n(Payer)" as D2
end box
box "DFSP B"
    participant "DFSP B\n(Payee)" as D3
end box
actor "Bhavesh\n(+44 1234 5678)" as CB


== Transfer Phase ==

... DFSP A initiates a normal Mojaloop P2P Transfer ...

D2 -> D2: Generate a new ""transferId"", and associate \n it with the ""transactionRequestId""

rnote over D2 #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "transferId": "321",
  "quoteId": "456",
  "payerFsp": "dfspa",
  "payeeFsp": "dfspb",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "expiration": "2020-06-15T13:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
D2 -> S: ""POST /transfers""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "transferId": "321",
  "quoteId": "456",
  "payerFsp": "dfspa",
  "payeeFsp": "dfspb",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "expiration": "2020-06-15T13:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
S -> D3: ""POST /transfers""
D3 --> S: ""202 Accepted""

rnote left of D3 #Light
**""PUT /transfers/321""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "fulfilment": "...",
  "completedTimestamp": "2020-06-15T12:01:00.000",
  "transferState": "COMMITTED"
}
end note
D3 -> S: ""PUT /transfers/321""
S --> D3: ""200 OK""
D3 -> CB: You have received funds from Ayeesha!
S -> D2: ""PUT /transfers/321""
D2 --> S: ""200 OK""


D2 -> D2: Look up ""transactionRequestId"" from the ""transferId""

rnote over D2 #Light
**""PATCH /thirdpartyRequests/transactions/00000000-0000-0000-0000-000000000000""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  "transactionId": "11111111-0000-0000-0000-000000000000",
  "transactionRequestState": "ACCEPTED",
  "transactionState": "COMMITTED"
}
end note
D2 -> S: ""PATCH /thirdpartyRequests/transactions""\n""   /00000000-0000-0000-0000-000000000000""
S --> D2: ""200 OK""

S -> D1: ""PATCH /thirdpartyRequests/transactions""\n""   /00000000-0000-0000-0000-000000000000""
D1 --> S: ""200 OK""

note over D1 
  PISP can now inform the user the 
  funds have been sent
end note

@enduml
