@startuml

title PISP Transfer

!include participants.iuml

== Agreement Phase ==

D2->S:Please provide me with a quotation for this transfer
activate S
S-->D2:202 I'll get back to you
deactivate D2
note over S

Again, this is a completely standard quote request
Note that it includes the transactionRequestId from the original request

FSPIOP-Source: DFSP A
FSPIOP-Destination: DFSP B

{
    "quoteId": "7c23e80c-d078-4077-8263-2c047876fcf6",
    "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
    "transactionRequestId": "8d34f91d-d078-4077-8263-2c047876fcf6",
    "payee": {
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "+44 1234 5678",
            "fspId": "DFSP B"
        }
    },
    "payer": {
        "personalInfo": {
            "complexName": {
                "firstName": "Ayesha",
                "lastName": "Takia"
            }
        },
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "+44 8765 4321",
            "fspId": "DFSP A"
        }
    },
    "amountType": "RECEIVE",
    "amount": {
        "amount": "100",
        "currency": "USD"
    },
    "transactionType": {
        "scenario": "TRANSFER",
        "initiator": "PAYER", 
        "initiatorType": "CONSUMER"
    },
    "expiration": "2020-02-15T22:17:28.985-01:00"
}
end note 

S->D3:Please quote on this proposed transfer
activate D3
D3-->S:202 I'll get back to you
deactivate S
D3->D3:Prepare the quotation
D3->S:Here is the quotation
activate S 
S-->D3:200 OK, got it
deactivate D3
note over S

Now we need to make a change to how things work now.
We need to report this information to the PISP,
so that it can:

a) Understand the progress of the transfer
b) Report on the terms of the transfer (e.g. fees) to the customer

end note

S->D2:Here is the quote response
activate D2
D2-->S:200 OK, got it
deactivate S
D2->D2:Is this a payee-initiated quote?\n(i.e. does the quote have a transactionRequestId?)
alt No, it isn't
D2->D2:Do nothing
else Yes, it is.
D2->D2:Find the related transaction request
D2->D2:Is the payee DFSP the same as the requester DFSP?
alt Yes, it is.
D2->D2:This is a payee-initiated transfer.\nDo nothing
else No, it isn't

D2->S:Please ask the customer to validate the transfer\n**POST /authorizations/{transactionRequestId}**
activate S
S-->D2:202 I'll get back to you

note over D2

This is a new HTTP Verb (POST) on the existing authorizations resource

""POST /authorizations/{transactionRequestId} HTTP/1.1""

FSPIOP-Source: DFSP A
FSPIOP-Destination: PISP???

TODO: Figure out the Request Body here
{
    "authenticationType": "???",
    "retriesLeft": "2",
    "amount": "101",
    "currency": "USD",
    "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
    "transactionRequestId": "8d34f91d-d078-4077-8263-2c047876fcf6",
    "quote": {
        "transferAmount": "101",
        "payeeReceiveAmount": "100",
        "payeeFspFee": "1",
        "expiration":"2020-02-15T22:17:28.985-01:00",
        "ilpPacket":"...",
        "condition":"..."
    }
}
end note 

deactivate D2
S->D1:Please ask the customer to validate the transfer\n**POST /authorizations/{transactionRequestId}**
activate D1
D1-->S:202 I'll get back to you
deactivate S
D1->D1:Get me the quote data for this transfer request
D1->App:Here are the terms for your customer's transfer
activate App
App-->D1:202 I'll get back to you
App->CA:Here are the terms for your transfer.\nPlease authenticate yourself and confirm\nthat you're happy to proceed
CA->App:Here's my fingerprint. I'm happy to proceed
App->D1:Customer has approved the terms.\nI have the signed Challenge
D1-->App:200 OK, got it
deactivate App
D1->S:Customer has confirmed the transfer\n**PUT /authorizations/{transactionRequestId}**
activate S
S-->D1:200 OK, got it
deactivate D1

S->A: Who manages fido for DFSP1?
activate A
A-->S: It's managed by the switch
deactivate A

S->FIDO: Here's a signed challenge and KeyId. Do these things match?
activate FIDO
FIDO-->S: 202 I'll get back to you
FIDO->S: Yep, this looks good to me
S-->FIDO: OK, got it
deactivate FIDO

note over FIDO
    TODO: 
    
    Where do we check that the Signed Challenge matches the condition/other feature of the transfer?
end note

S->D2:Customer has confirmed the transfer\nFIDO Server has verified transfer
activate D2
D2-->S:200 OK, got it
deactivate S
D2->D2:Store the transfer request number against\nthe transaction number given in the quote.\nThis will be useful when the transfer comes back 


end
end


@enduml