@startuml

title Transfer: 3.4.1 Bad Signed Challenge - Self Hosted Auth-Service


box "PISP"
participant "PISP Server" as D1
end box
box "Mojaloop"
    participant Switch as S
end box
box "DFSP A"
    participant "DFSP A\n(Payer)" as D2
end box
box "DFSP B"
    participant "DFSP B\n(Payee)" as D3
end box

... PISP has initiated Thirdparty Transaction Request with ""POST /thirdpartyRequests/transactions""...

... DFSP A has received quote, and asked PISP to verify...

note right of D1
  PISP looks up the ""transactionRequestId"" and
  checks the quote with the user,
  and uses the FIDO API to sign the 
  the **""challenge""** string
end note

rnote right of D1 #Light
**""PUT /thirdpartyRequests/authorizations/33333333-0000-0000-0000-000000000000""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed challenge>",
      "counter": "1"
    }
  }
  "responseType": "ENTERED"
}
end note
D1 -> S: ""PUT /thirdpartyRequests/authorizations/33333333-0000-0000-0000-000000000000""
S --> D1: ""200 OK""
S -> D2: ""PUT /thirdpartyRequests/authorizations""\n""/33333333-0000-0000-0000-000000000000""
D2 --> S: ""200 OK""

D2 -> D2: Look up the ""transactionRequestId"" for this ""authorizationId""
D2 -> D2: Look up the ""consentId"" for this ""transactionRequestId""
D2 -> D2: Look up the ""publicKey"" for this ConsentId. Check the signing of the signed challenge

note over D2
  Signed challenge is invalid. Transaction Request failed.
end note


rnote left of D2 #Light
**""PUT /thirdpartyRequests/transactions""**
**""    /00000000-0000-0000-0000-000000000000/error""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  "errorInformation": {
    "errorCode": "6200",
    "errorDescription": "Invalid signed challenge",
    "extensionList": []
  }
}
end note
D2 -> S: ""PUT /thirdpartyRequests/transactions""\n""    /00000000-0000-0000-0000-000000000000/error""
S --> D2: ""200 OK""
S -> D1: ""PUT /thirdpartyRequests/transactions""\n""    /00000000-0000-0000-0000-000000000000/error""
D1 --> S: ""200 OK""

@enduml
