@startuml

title PISP Transfer

!include participants.iuml

== Transfer Phase ==
autonumber 1 "<b>TR-#</b>"

...
note over S
    A standard Normal P2P Transfer from
    DFSPA -> DFSPB now takes place
end note
...


S->S: Does that transfer that just took place relate to a PISP transfer?
note over S

We're in the Yes box, so, er, yes.

end note

S->S: Lookup the \n""thirdPartyTransferId"" associated with the transfer


S->D1:Here's the status of the transfer you asked for\n""PUT /thirdPartyRequest/transfer/{ID}""
activate D1
D1-->S:200 OK, got it
deactivate S 
D1->App:Transfer was successful
activate App
App->CA:Your funds were successfully transferred to Bhavesh.
CA-->App:Thank you very much.
deactivate App
deactivate D1


@enduml