@startuml

title PISP Transfer

!include participants.iuml

== Transfer Phase ==

note over D2

So now Ayesha's bank knows that she has confirmed
that she wants to complete the transfer on the terms
offered by Bhavesh's DFSP. The bank can go ahead
and request the transfer.

It does this in the normal way, and we pick the story
up again when the successful transfer message is received
by DFSP A

end note

D2->D2:Do I have a transfer request associated\nwith this transaction?
note over D2

We're in the Yes box, so, er, yes.

end note

D2->S:Forward the transfer response to the PISP
activate S
S-->D2:200 OK, got it
deactivate D2
note over S

This too is syntactically ugly, because you shouldn't send
a **PUT** except in response to a request. But we'll worry
about that later...

end note
S->D1:Here's the status of the transfer you asked for
activate D1
D1-->S:200 OK, got it
deactivate S 
D1->D1:WTF?
D1->D1:Oh, OK. I can see that this is a response\nto a transfer request.\nI'll look up the quote with this transaction ID\n and use it to find the transfer request
D1->App:Transfer was successful
activate App
App->CA:Your funds were successfully\ntransferred to Bhavesh.
CA-->App:Thank you very much.
deactivate App
deactivate D1


' end
' end


@enduml