@startuml

title PISPTransferDetailedAPI

!include participants_api.iuml

== Discovery (Lookup) ==
rnote right of D1 #Light
**""GET /parties/MSISDN/+4412345678""**
""FSPIOP-Source: pispa""
end note
D1 -> S: ""GET /parties/MSISDN/+4412345678""
S --> D1: ""202 Accepted""

... ALS lookup flow not shown here ...

rnote over S #Light
**""GET /parties/MSISDN/+4412345678""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspb""
end note
S -> D3: ""GET /parties/MSISDN/+4412345678""
D3 --> S: ""202 Accepted""

rnote left of D3 #Light
**""PUT /parties/MSISDN/+4412345678""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: pispa""
{
  partyIdType: "MSISDN",
  partyIdentifier: "+4412345678",
  party: {
    partyIdInfo: {
      partyIdType: "MSISDN",
      partyIdentifier: "+4412345678",
      fspId: 'dfspb",
    },
    name: "Bhavesh S.",
    accounts: [
      {
        "address": "dfspb.8f027046-b82a-4fa9-838b-70210fcf8137",
        "currency": "USD"
      }
    ]
  }
}
end note
D3 -> S: ""PUT /parties/MSISDN/+4412345678""
S --> D3: ""200 OK""

rnote over S #Light
**""PUT /parties/MSISDN/+4412345678""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: pispa""
{
  partyIdType: "MSISDN",
  partyIdentifier: "+4412345678",
  party: {
    partyIdInfo: {
      partyIdType: "MSISDN",
      partyIdentifier: "+4412345678",
      fspId: 'dfspb",
    },
    name: "Bhavesh S.",
    accounts: [
      {
        "address": "dfspb.8f027046-b82a-4fa9-838b-70210fcf8137",
        "currency": "USD"
      }
    ]
  }
}
end note
S -> D1: ""PUT /parties/MSISDN/+4412345678""
D1 --> S: ""200 OK""

... PISP confirms payee party with their user ...

newpage

== Agreement Phase ==
rnote right of D1 #Light
**""POST /thirdpartyRequests/transactions""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "transactionRequestId": "123",
  //This tells dfspa which account to deduct funds from
  //it's an opaque identifier that the DFSP knows about
  **"sourceAccountId": "dfspa.1111-2222",**
  //This tells dfspa and auth-service which consent allows the pisp to initiate this tx
  **"consentId": "111"**
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "expiration": "2020-06-15T22:17:28.985-01:00"
}
end note
D1 -> S: ""POST /thirdpartyRequests/transactions""
S --> D1: ""202 Accepted""

rnote over S #Light
**""POST /thirdpartyRequests/transactions""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "transactionRequestId": "123",
  //This tells dfspa which account to deduct funds from
  //it's an opaque identifier that the DFSP knows about
  **"sourceAccountId": "dfspa.1111-2222",**
  //This tells dfspa and auth-service which consent allows the pisp to initiate this tx
  **"consentId": "111"**
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    },
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "expiration": "2020-06-15T00:00:00.000"
}
end note
S -> D2: ""POST /thirdpartyRequests/transactions""
D2 --> S: ""202 Accepted""
D2 -> D2: Lookup this ""consentId"", ""sourceAccountId"" \nand ""pispId"". Verify that they exist, and consent \nis granted with a valid credential
D2 -> D2: Generate a unique transactionId for this transaction request: ""987""


rnote left of D2 #Light
**""PUT /thirdpartyRequests/transactions/123""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  "transactionId": "987",
  "transactionRequestState": "RECEIVED"
}
end note
D2 -> S: ""PUT /thirdpartyRequests/transactions/123""
S --> D2: ""200 OK""

rnote over S #Light
**""PUT /thirdpartyRequests/transactions/123""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  "transactionId": "987",
  "transactionRequestState": "RECEIVED"
}
end note
S -> D1: ""PUT /thirdpartyRequests/transactions/123""
D1 --> S: ""200 OK""



rnote left of D2 #Light
**""POST /quotes""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "quoteId": "456", //Set by the payer dfsp
  "transactionId": "987", //Set by the payer dfsp
  *"transactionRequestId": "123", //Relates to the original thirdpartyRequest!*
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    },
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "quote note"
}
end note
D2 -> S: ""POST /quotes""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /quotes""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "quoteId": "456", //Set by the payer dfsp
  "transactionId": "987", //Set by the payer dfsp
  *"transactionRequestId": "123", //Relates to the original thirdpartyRequest!*
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    },
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "quote note"
}
end note
S -> D3: ""POST /quotes""
D3 --> S: ""202 Accepted""

rnote left of D2 #Light
**""PUT /quotes/456""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "transferAmount": {
    "amount": "100",
    "currency": "USD"
  },
  "payeeReceiveAmount": {
    "amount": "99",
    "currency": "USD"
  },
  "payeeFspFee": {
    "amount": "1",
    "currency": "USD"
  },
  "expiration": "2020-06-15T12:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
D3 -> S: ""PUT /quotes/456""
S --> D3: ""200 OK""

rnote left of D2 #Light
**""PUT /quotes/456""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "transferAmount": {
    "amount": "100",
    "currency": "USD"
  },
  "payeeReceiveAmount": {
    "amount": "99",
    "currency": "USD"
  },
  "payeeFspFee": {
    "amount": "1",
    "currency": "USD"
  },
  "expiration": "2020-06-15T12:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
S -> D2: ""PUT /quotes/456""
D2 --> S: ""200 OK""

note left of D2
  DFSPA has the quote, they can now ask
  the PISP for authorization
end note

rnote left of D2 #Light
**""POST /authorizations""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  //transactionRequestId is our 'primary key'
  //to refer to this authorization
  **"transactionRequestId": "123",**
  "authenticationType": "U2F",
  "retriesLeft": "1",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionId": "987",
  "quote": {
    //TODO: do we need quoteId here?
    "transferAmount": {
      "amount": "100",
      "currency": "USD"
    },
    "payeeReceiveAmount": {
      "amount": "99",
      "currency": "USD"
    },
    "payeeFspFee": {
      "amount": "1",
      "currency": "USD"
    },
    "expiration": "2020-06-15T12:00:00.000",
    "ilpPacket": "...",
    "condition": "...",
  }
}
end note
D2 -> S: ""POST /authorizations""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /authorizations""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  //transactionRequestId is our 'primary key'
  //to refer to this authorization
  **"transactionRequestId": "123",**
  "authenticationType": "U2F",
  "retriesLeft": "1",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionId": "987",
  "quote": {
    "transferAmount": {
      "amount": "100",
      "currency": "USD"
    },
    "payeeReceiveAmount": {
      "amount": "99",
      "currency": "USD"
    },
    "payeeFspFee": {
      "amount": "1",
      "currency": "USD"
    },
    "expiration": "2020-06-15T12:00:00.000",
    "ilpPacket": "...",
    "condition": "...",
  }
}
end note
S -> D1: ""POST /authorizations""
D1 --> S: ""202 Accepted""

note right of D1
  PISP checks the quote with the user,
  and uses FIDO to sign the the QuoteResponse object
end note

rnote right of D1 #Light
**""PUT /authorizations/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed QuoteResponse>",
      "counter": "1"
    }
  }
  "responseType": "ENTERED"
}
end note
D1 -> S: ""PUT /authorizations/123""

S --> D1: ""200 OK""


rnote over S #Light
**""PUT /authorizations/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed QuoteResponse>",
      "counter": "1"
    }
  }
  "responseType": "ENTERED"
}
end note
S -> D2: ""PUT /authorizations/123""
D2 --> S: ""200 OK""


D2 -> D2: Lookup the ""thirdpartyRequests/transaction""\nrequest, get the ""consentId"" and ""sourceAccountId""
D2 -> D2: Confirm pispId from ""PUT /authorizations/123""\n matches the ""thirdpartyRequests/transaction""

note over D2
  Switch has the signed condition
  For 3rd party FIDO, it now needs to make sure everything checks out
end note

rnote left of D2 #Light
**""POST /thirdpartyRequests/transactions/123/authorizations""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: central-auth""
{
  //from ""PUT /quotes/456"" callback
  "challenge": "<QuoteResponse object>",

  //from ""PUT /authorizations/123"" callback: .authenticationInfo.authenticationValue.pinValue
  "value": "<base64 encoded binary - the signed quote response object>",

  //from ""thirdpartyRequests/transactions"" body
  "consentId": "111",

  //from ""thirdpartyRequests/transactions"" body
  "sourceAccountId": "dfspa.1111-2222"
}
end note
D2 -> S: ""POST /thirdpartyRequests/transactions/123/authorizations""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /thirdpartyRequests/transactions/123/authorizations""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: central-auth""
{
  //from ""PUT /quotes/456"" callback
  "challenge": "<QuoteResponse object>",

  //from ""PUT /authorizations/123"" callback: .authenticationInfo.authenticationValue.pinValue
  "value": "<base64 encoded binary - the signed quote response object>",

  //from ""thirdpartyRequests/transactions"" body
  "consentId": "111",

  //from ""thirdpartyRequests/transactions"" body
  "sourceAccountId": "dfspa.1111-2222",

  "status": "PENDING"
}
end note
S -> AUTHS: ""POST /thirdpartyRequests/transactions/123/authorizations""
AUTHS --> S: ""202 Accepted""

AUTHS -> AUTHS: Lookup this consent based on consentId
AUTHS -> AUTHS: Ensure the sourceAccountId matches what is in Consent
AUTHS -> AUTHS: Check that the signed bytes match the \npublickey we have stored for the consent

rnote right of AUTHS #Light
**""PUT /thirdpartyRequests/transactions/123/authorizations""**
""FSPIOP-Source: central-auth""
""FSPIOP-Destination: dfspa""
{
  //from the ""PUT /quotes/456"" callback
  "challenge": "<QuoteResponse object>",

  //from the ""PUT /authorizations/123"" callback
  "value": "<base64 encoded binary - the signed quote response object>",

  //from the ""thirdpartyRequests/transactions"" body
  "consentId": "111",

  //from the ""thirdpartyRequests/transactions"" body
  "sourceAccountId": "dfspa.1111-2222"
  "status": "VERIFIED"
}
end note
AUTHS -> S: ""PUT /thirdpartyRequests/transactions/123/authorizations""
S --> AUTHS: ""200 OK""

rnote over S #Light
**""PUT /thirdpartyRequests/transactions/123/authorizations""**
""FSPIOP-Source: central-auth""
""FSPIOP-Destination: dfspa""
{
  //from the ""PUT /quotes/456"" callback
  "challenge": "<QuoteResponse object>",

  //from the ""PUT /authorizations/123"" callback
  "value": "<base64 encoded binary - the signed quote response object>",

  //from the ""thirdpartyRequests/transactions"" body
  "consentId": "111",

  //from the ""thirdpartyRequests/transactions"" body
  "sourceAccountId": "dfspa.1111-2222"
  "status": "VERIFIED"
}
end note
S -> D2: ""PUT /thirdpartyRequests/transactions/123/authorizations""
D2 --> S: ""200 OK""

note over D2
  DFSPA now knows that the user signed this transaction
  and can go ahead and initiate the transfer
end note

newpage

== Transfer Phase ==

rnote over D2 #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "transferId": "321",
  "quoteId": "456",
  "payerFsp": "dfspa",
  "payeeFsp": "dfspb",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "expiration": "2020-06-15T13:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
D2 -> S: ""POST /transfers""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "transferId": "321",
  "quoteId": "456",
  "payerFsp": "dfspa",
  "payeeFsp": "dfspb",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "expiration": "2020-06-15T13:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
S -> D3: ""POST /transfers""
D3 --> S: ""202 Accepted""

rnote left of D3 #Light
**""PUT /transfers/321""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "fulfilment": "...",
  "completedTimestamp": "2020-06-15T12:01:00.000",
  "transferState": "COMMITTED"
}
end note
D3 -> S: ""PUT /transfers/321""
S --> D3: ""200 OK""

rnote over S #Light
**""PUT /transfers/321""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "fulfilment": "...",
  "completedTimestamp": "2020-06-15T12:01:00.000",
  "transferState": "COMMITTED"
}
end note
S -> D2: ""PUT /transfers/321""
D2 --> S: ""200 OK""


rnote over S #Light
**""PATCH /thirdpartyRequests/transactions/123""**
""FSPIOP-Source: switch""
""FSPIOP-Destination: pispa""
{
  "transactionId": "987",
  "transactionRequestState": "ACCEPTED",
  "transactionState": "COMMITTED"
}
end note
S -> D1: ""PATCH /thirdpartyRequests/transactions/123""
D1 --> S: ""200 OK""


@enduml
