@startuml

title PISPTransferDetailedAPI

!include participants_api.iuml

== Discovery (Lookup) ==
rnote right of D1 #Light
**""GET /parties/MSISDN/+4412345678""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: switch""
end note
D1 -> S: ""GET /parties/MSISDN/+4412345678""
S --> D1: ""202 Accepted""

... ALS lookup flow not shown here ...

rnote over S #Light
**""GET /parties/MSISDN/+4412345678""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspb""
end note
S -> D3: ""GET /parties/MSISDN/+4412345678""
D3 --> S: ""202 Accepted""

rnote left of D3 #Light
**""PUT /parties/MSISDN/+4412345678""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: pispa""
{
  partyIdType: "MSISDN",
  partyIdentifier: "+4412345678",
  party: {
    partyIdInfo: {
      partyIdType: "MSISDN",
      partyIdentifier: "+4412345678",
      fspId: 'dfspb",
    },
    name: "Bhavesh S.",
    accounts: [
      {
        "address": "dfspb.8f027046-b82a-4fa9-838b-70210fcf8137",
        "currency": "USD"
      }
    ]
  }
}
end note
D3 -> S: ""PUT /parties/MSISDN/+4412345678""
S --> D3: ""202 Accepted""

rnote over S #Light
**""PUT /parties/MSISDN/+4412345678""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: pispa""
{
  partyIdType: "MSISDN",
  partyIdentifier: "+4412345678",
  party: {
    partyIdInfo: {
      partyIdType: "MSISDN",
      partyIdentifier: "+4412345678",
      fspId: 'dfspb",
    },
    name: "Bhavesh S.",
    accounts: [
      {
        "address": "dfspb.8f027046-b82a-4fa9-838b-70210fcf8137",
        "currency": "USD"
      }
    ]
  }
}
end note
S -> D1: ""PUT /parties/MSISDN/+4412345678""
D1 --> S: ""202 Accepted""

... PISP confirms payee party with their user ...

== Agreement Phase ==
rnote right of D1 #Light
**""POST /thirdpartyRequests/transfers""**
//TODO is this right? Michael had source as dfspa...
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "quoteId": "456",
  "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
  "transactionRequestId": "123",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  //TODO: source account id!
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER", 
    "initiatorType": "CONSUMER"
  },
  "expiration": "2020-06-15T22:17:28.985-01:00"
}
end note
D1 -> S: ""POST /thirdpartyRequests/transfers""
S --> D1: ""202 Accepted""

rnote over S #Light
**""POST /thirdpartyRequests/transfers""**
//TODO is this right? Michael had source as dfspa...
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "quoteId": "456",
  "transactionId": "987",
  "transactionRequestId": "123",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    },
    //This tells dfspa which account to deduct funds from
    **"sourceAccountId": "dfspa",**
    //This tells dfspa and auth-service which consent allows the pisp to initiate this tx
    **"consentId": "111"**
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER", 
    "initiatorType": "CONSUMER"
  },
  "expiration": "2020-06-15T00:00:00.000"
}
end note
S -> D2: ""POST /thirdpartyRequests/transfers""
D2 --> S: ""202 Accepted""

rnote left of D2 #Light
**""POST /quotes""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "quoteId": "456",
  "transactionId": "987",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    },
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "quote note"
}
end note
D2 -> S: ""POST /quotes""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /quotes""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "quoteId": "456",
  "transactionId": "987",
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+4412345678",
      "fspId": "dfspb"
    }
  },
  "payer": {
    "personalInfo": {
      "complexName": {
        "firstName": "Ayesha",
        "lastName": "Takia"
      }
    },
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "+44 8765 4321",
      "fspId": "dfspa"
    },
  },
  "amountType": "SEND",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "quote note"
}
end note
S -> D3: ""POST /quotes""
D2 --> S: ""202 Accepted""

rnote left of D2 #Light
**""PUT /quotes/456""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "transferAmount": {
    "amount": "100",
    "currency": "USD"
  },
  "payeeReceiveAmount": {
    "amount": "99",
    "currency": "USD"
  },
  "payeeFspFee": {
    "amount": "1",
    "currency": "USD"
  },
  "expiration": "2020-06-15T12:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
D3 -> S: ""PUT /quotes/456""
S --> D3: ""202 Accepted""

rnote left of D2 #Light
**""PUT /quotes/456""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "transferAmount": {
    "amount": "100",
    "currency": "USD"
  },
  "payeeReceiveAmount": {
    "amount": "99",
    "currency": "USD"
  },
  "payeeFspFee": {
    "amount": "1",
    "currency": "USD"
  },
  "expiration": "2020-06-15T12:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
S -> D2: ""PUT /quotes/456""
D2 --> S: ""202 Accepted""

rnote left of D2 #Light
**""POST /authorizations""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{      
  "authenticationType": "U2F",
  "retriesLeft": 1,
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionId": "987",
  "transactionRequestId": "123",
  "quote": {
    "transferAmount": {
      "amount": "100",
      "currency": "USD"
    },
    "payeeReceiveAmount": {
      "amount": "99",
      "currency": "USD"
    },
    "payeeFspFee": {
      "amount": "1",
      "currency": "USD"
    },
    "expiration": "2020-06-15T12:00:00.000",
    "ilpPacket": "...",
    "condition": "...",
  }
}
end note
D2 -> S: ""POST /authorizations""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /authorizations""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{      
  "authenticationType": "U2F",
  "retriesLeft": 1,
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "transactionId": "987",
  "transactionRequestId": "123",
  "quote": {
    "transferAmount": {
      "amount": "100",
      "currency": "USD"
    },
    "payeeReceiveAmount": {
      "amount": "99",
      "currency": "USD"
    },
    "payeeFspFee": {
      "amount": "1",
      "currency": "USD"
    },
    "expiration": "2020-06-15T12:00:00.000",
    "ilpPacket": "...",
    "condition": "...",
  }
}
end note
S -> D1: ""POST /authorizations""
D1 --> S: ""202 Accepted""

...PISP checks the quote with the user, and uses FIDO to sign the ""quote.condition""...
rnote right of D1 #Light
**""PUT /authorizations/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed condition>",
      "counter": 1
    }
  }
  "responseType": "ENTERED"
}
end note
D1 -> S: ""PUT /authorizations/123""
note right of D1 
  Note! we use the ""transactionRequestId"" here in the ""PUT""
end note
S --> D1: ""202 Accepted""

note over S
  Switch finds out who takes care of the auth-service for dfspa
end note

rnote over S #Light
**""GET /participants/AUTHSERVICE/dfspa""**
end note
S -> A: ""GET /participants/AUTHSERVICE/dfspa""
rnote over A #Light
  ""{"fspId":"switch"}""
end note
A --> S: ""{"fspId":"switch"}""

rnote over S #Light
**""PUT /authorizations/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed condition>",
      "counter": 1
    }
  }
  "responseType": "ENTERED"
}
end note
S -> AUTHS: ""PUT /authorizations/789""
AUTHS --> S: ""202 Accepted""

note over AUTHS
  Auth Service checks the signed challenge against the
  previously registered public key
end note

rnote over AUTHS #Light
//TODO: The AuthService has no context about the ""thirdpartyRequest"" or ""quote""!!
how can it:
1. get the consentId?
2. get the condition (challenge) that has been signed?
3. check that the condition matches a quote?

**""PUT /authorizations/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed condition>",
      "counter": 1
    }
  }
  "responseType": "ENTERED"
}
end note
AUTHS -> S: ""PUT /authorizations/123""
S --> AUTHS: ""202 Accepted""

rnote over S #Light
**""PUT /authorizations/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
{
  "authenticationInfo": {
    "authentication": "U2F",
    "authenticationValue": {
      "pinValue": "<base64 encoded binary - the signed condition>",
      "counter": 1
    }
  }
  "responseType": "ENTERED"
}
end note
S -> D2: ""PUT /authorizations/123""
D2 --> S: ""202 Accepted""

== Transfer Phase ==

rnote over D2 #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "transferId": "321",
  "quoteId": "456",
  "payerFsp": "dfspa",
  "payeeFsp": "dfspb",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "expiration": "2020-06-15T13:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
D2 -> S: ""POST /transfers""
S --> D2: ""202 Accepted""

rnote over S #Light
**""POST /transfers""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: dfspb""
{
  "transferId": "321",
  "quoteId": "456",
  "payerFsp": "dfspa",
  "payeeFsp": "dfspb",
  "amount": {
    "amount": "100",
    "currency": "USD"
  },
  "expiration": "2020-06-15T13:00:00.000",
  "ilpPacket": "...",
  "condition": "...",
}
end note
S -> D3: ""POST /transfers""
D3 --> S: ""202 Accepted""

rnote left of D3 #Light
**""PUT /transfers/321""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "fulfilment": "...",
  "completedTimestamp": "2020-06-15T12:01:00.000",
  "transferState": "COMMITTED"
}
end note
D3 -> S: ""PUT /transfers/321""
S --> D3: ""202 Accepted""

rnote over S #Light
**""PUT /transfers/321""**
""FSPIOP-Source: dfspb""
""FSPIOP-Destination: dfspa""
{
  "fulfilment": "...",
  "completedTimestamp": "2020-06-15T12:01:00.000",
  "transferState": "COMMITTED"
}
end note
S -> D2: ""PUT /transfers/321""
D2 --> S: ""202 Accepted""


rnote over S #Light
**""PUT /thirdpartyRequests/transactions/123""**
""FSPIOP-Source: switch""
""FSPIOP-Destination: pispa""
{
  "transactionId": "987",
  "transactionRequestState": "ACCEPTED"
}
end note
S -> D1: ""PUT /thirdpartyRequests/transactions/123""
D1 --> S: ""202 Accepted""


@enduml