@startuml

title PISPGetTransactionRequest

!include participants_api.iuml
autonumber 1 "<b>GTR-#</b>"

note over S
  Assuming a previously created thirdparty transaction request with id: ""123""

end note

rnote right of D1 #Light
**""GET /thirdpartyRequests/transactions/123""**
""FSPIOP-Source: pispa""
""FSPIOP-Destination: dfspa""
end note

D1 -> S: ""GET /thirdpartyRequests/transactions/123""
S --> D1: ""202 Accepted""

S -> D2: ""GET /thirdpartyRequests/transactions/123""
D2 --> S: ""202 Accepted""

D2 -> D2: DFSP looks up already created \nthirdparty transaction request
D2 -> D2: DFSP ensures that the FSPIOP-Source (pisp)\nis the same as the original sender of \n""POST /thirdpartyRequests/transactions/123""

rnote left of D2 #Light
**""PUT /thirdpartyRequests/transactions/123""**
""FSPIOP-Source: dfspa""
""FSPIOP-Destination: pispa""
{
  "transactionId": "987",
  "transactionRequestState": "ACCEPTED"
}
end note
D2 -> S: ""PUT /thirdpartyRequests/transactions/123""
S --> D2: ""200 OK""

S -> D1: ""PUT /thirdpartyRequests/transactions/123""
D1 --> S: ""200 OK""

@enduml
