box "Mobile device"
    actor "Ayesha\n(+44 8765 4321)" as CA
    participant "PISP App" as App
end box
box "PISP"
participant "PISP Server" as D1
end box
box "Mojaloop"
    participant "FIDO Server" as FIDO
    participant Switch as S
    participant "ALS" as A
end box
box "DFSP A"
    participant "DFSP A\n(Payer)" as D2
end box
box "DFSP B"
    participant "DFSP B\n(Payee)" as D3
end box
actor "Bhavesh\n(+44 1234 5678)" as CB
