box "PISP"
participant "PISP Server" as D1
end box
box "Mojaloop"
    participant "auth-service" as AUTHS
    participant Switch as S
    participant "ALS" as A
end box
box "DFSP A"
    participant "DFSP A\n(Payer)" as D2
end box
box "DFSP B"
    participant "DFSP B\n(Payee)" as D3
end box
