@startuml

title PISP transfer model\n(using Merchant Request to Pay Model)

actor Ayesha as CA
participant "PISP App" as App
participant "PISP Server\n(DFSP)" as D1
participant "Switch" as S
participant "ALS" as A 
participant "Payer DFSP\n(DFSP A)" as D2
participant "Payee DFSP\n(DFSP B)" as D3
actor "Bhavesh\n(B@Somewhere)" as CB

note over S
This proposal does not require changes to API or switch.
DFSPs who participate in the scheme will need to make two changes:

1) If the transfer is initiated by a PISP, copy the quote response to the PISP
2) If the transfer is initiated by a PISP, copy the transfer response to the PISP

Logic to be used to ascertain whether or not the transfer is initiated by a PIPSP
is shown in line.

It is assumed that:
-> all customer authentication is carried out on the customer's device
-> DFSP duties in relation to PISP transfers are defined in the scheme rules and operating guidelines
end note

== Discovery phase ==

CA->App: I would like to transfer\n$100 to B@Somewhere
activate App
App->D1: Ayesha would like to transfer\n$100 to B@Somewhere
activate D1
D1-->App: Got it.
deactivate App
D1->D1: What is Ayesha's payer key?\nIt's A@Elsewhere
D1->S: Which DFSP owns A@Elsewhere?\n(**GET /parties**)
activate S 
S-->D1: ""202"": I'll get back to you
deactivate D1
S->A: Which DFSP owns A@Elsewhere?
activate A 
A-->S: It's DFSP A
deactivate A
S->D1: DFSP A speaks for A@Elsewhere
activate D1
D1-->S: ""200"": OK, got it
deactivate S

note over D1
The PISP server doesn't need to know
where to send the payment: this will
be handled as part of the transfer from
DFSP A
end note 

D1->S: Which DFSP owns B@Somewhere?\n(**GET /parties**)
activate S 
S-->D1: 202 I'll get back to you
deactivate D1
S->A: Which DFSP owns B@Somewhere?
activate A 
A-->S: It's DFSP B
deactivate A
S->D3: Do you speak for B@Somewhere?
activate D3
D3-->S: ""202"": I'll get back to you
deactivate S
D3->D3: Retrieve customer information for Bhavesh
D3->S: Here's Bhavesh's personal information
activate S 
S-->D3: ""200"": OK, got it
deactivate D3

S->D1: DFSP A speaks for B@Somewhere\nThe customer is Bhavesh
activate D1
D1-->S: ""200"": OK, got it
deactivate S
D1->App: System reports\ncustomer name is Bhavesh
activate App
App->CA: That's Bhavesh, right?
CA-->App: Yes, it is
App->D1: Customer is happy that she's\nsending to the right recipient
deactivate App

note over D1
So now I know both the actual parties:
- DFSP A is the payer DFSP
- DFSP B is the payee DFSP

Now I need to request DFSP A to make the payment
end note

D1->S: Please ask DFSP A to transfer\n$100 from Ayesha to Bhavesh
activate S 
S-->D1: 202 I'll get back to you 
deactivate D1

note over S
The switch receives a message that looks like the one below.
It's a standard Mojaloop message

POST /transactionRequests HTTP/1.1\n\

FSPIOP-Source: PISP
FSPIOP-Destination: DFSP A 

{
    "transactionRequestId": "8d34f91d-d078-4077-8263-2c047876fcf6",
    "payee": {
        "partyIdInfo": {
            "partyIdType": "ALIAS",
            "partyIdentifier": "B@Somewhere", 
            "fspId": "DFSP B"
        }
    },
    "payer": {
        "personalInfo": {
            "complexName": {
                "firstName": "Ayesha",
                "lastName": "Takia"
            }
        },
        "partyIdInfo": {
            "partyIdType": "ALIAS",
            "partyIdentifier": "A@Elsewhere",
            "fspId": "DFSP A"
        }
    },
    "amountType": "RECEIVE",
    "amount": {
        "amount": "100",
        "currency": "USD"
    },
    "transactionType": {
        "scenario": "TRANSFER",
        "initiator": "PAYER",
        "initiatorType": "CONSUMER"
    },
    "note": "Ayesha via PISP",
    "expiration": "2020-02-15T22:17:28.985-01:00"
    ]
}
""

end note 
S->S: Store this request
S->D2: Please ask DFSP A to transfer\n$100 from Ayesha to Bhavesh
activate D2
D2-->S: 202 I'll get back to you
deactivate S
D2->D2: Store this request

== Agreement Phase ==

D2->S: Please provide me with a quotation for this transfer
activate S
S-->D2: 202 I'll get back to you
deactivate D2
note over S

Again, this is a completely standard quote request
Note that it includes the transactionRequestId from the original request

FSPIOP-Source: DFSP A
FSPIOP-Destination: DFSP B

{
    "quoteId": "7c23e80c-d078-4077-8263-2c047876fcf6",
    "transactionId": "85feac2f-39b2-491b-817e-4a03203d4f14",
    "transactionRequestId": "8d34f91d-d078-4077-8263-2c047876fcf6",
    "payee": {
        "partyIdInfo": {
            "partyIdType": "ALIAS",
            "partyIdentifier": "B@Somewhere",
            "fspId": "DFSP B"
        }
    },
    "payer": {
        "personalInfo": {
            "complexName": {
                "firstName": "Ayesha",
                "lastName": "Takia"
            }
        },
        "partyIdInfo": {
            "partyIdType": "ALIAS",
            "partyIdentifier": "A@Elsewhere",
            "fspId": "DFSP A"
        }
    },
    "amountType": "RECEIVE",
    "amount": {
        "amount": "100",
        "currency": "USD"
    },
    "transactionType": {
        "scenario": "TRANSFER",
        "initiator": "PAYER", 
        "initiatorType": "CONSUMER"
    },
    "expiration": "2020-02-15T22:17:28.985-01:00"
}
end note 

S->D3: Please quote on this proposed transfer
activate D3
D3-->S: 202 I'll get back to you
deactivate S
D3->D3: Prepare the quotation
D3->S: Here is the quotation
activate S 
S-->D3: 200 OK, got it
deactivate D3

note over S
Now we need to make a change to how things work now.
We need to report this information to the PISP,
so that it can:

a) Understand the progress of the transfer
b) Report on the terms of the transfer (e.g. fees) to the customer
end note

S->D2: Here is the quote response
activate D2
D2-->S: 200 OK, got it
deactivate S
D2->D2: Is this a payee-initiated quote?\n(i.e. does the quote have a transactionRequestId?)
alt No, it isn't
D2->D2: Do nothing
else Yes, it is.
D2->D2: Find the related transaction request
D2->D2: Is the payee DFSP the same as the requester DFSP?
alt Yes, it is.
D2->D2: This is a payee-initiated transfer.\nDo nothing
else No, it isn't
D2->S: Forward the quote response to the PISP
activate S
S-->D2: 200 OK, got it

note over S
This is syntactically ugly, because you shouldn't send
a **PUT** except in response to a request. But we'll worry
about that later...
end note

S->D1: Here's the quote you asked for
activate D1
D1-->S: 200 OK, got it
deactivate S 
D1->D1: WTF?
D1->D1: Oh, OK. I can see that this is a response\nto a transfer request. I'll look up the transfer request
D1->D1: Store the quote with the transfer request
deactivate D1
D2->S: Please ask the customer to validate the transfer\n**GET /authorizations/transactionRequestId**
activate S
S-->D2: 202 I'll get back to you
deactivate D2
S->D1: Please ask the customer to validate the transfer\n**GET /authorizations/transactionRequestId**
activate D1
D1-->S: 202 I'll get back to you
deactivate S
D1->D1: Get me the quote data for this transfer request
D1->App: Here are the terms for your customer's transfer
activate App
App-->D1: 202 I'll get back to you
App->CA: Here are the terms for your transfer.\nPlease authenticate yourself and confirm\nthat you're happy to proceed
CA->App: Here's my fingerprint. I'm happy to proceed
App->D1: Customer has approved the terms.
D1-->App: 200 OK, got it
deactivate App
D1->S: Customer has confirmed the transfer
activate S
S-->D1: 200 OK, got it
deactivate D1
S->D2: Customer has confirmed the transfer
activate D2
D2-->S: 200 OK, got it
deactivate S
D2->D2: Store the transfer request number against\nthe transaction number given in the quote.\nThis will be useful when the transfer comes back 

== Transfer Phase ==

note over D2
So now Ayesha's bank knows that she has confirmed
that she wants to complete the transfer on the terms
offered by Bhavesh's DFSP. The bank can go ahead
and request the transfer.

It does this in the normal way, and we pick the story
up again when the successful transfer message is received
by DFSP A
end note

D2->D2: Do I have a transfer request associated\nwith this transaction?
note over D2
We're in the Yes box, so, er, yes.
end note

D2->S: Forward the transfer response to the PISP
activate S
S-->D2: 200 OK, got it
deactivate D2

note over S
This too is syntactically ugly, because you shouldn't send
a **PUT** except in response to a request. But we'll worry
about that later...
end note

S->D1: Here's the status of the transfer you asked for
activate D1
D1-->S: 200 OK, got it
deactivate S 
D1->D1: WTF?
D1->D1: Oh, OK. I can see that this is a response\nto a transfer request.\nI'll look up the quote with this transaction ID\n and use it to find the transfer request
D1->App: Transfer was successful
activate App
App->CA: Your funds were successfully transferred to Bhavesh.
CA-->App: Thank you very much.
deactivate App
deactivate D1

end
end

@enduml